---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/blogs":
    post:
      summary: create blog
      description: Creates a blog
      tags:
      - Blogs
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                image_path:
                  type: string
    get:
      summary: list blogs
      responses:
        '200':
          description: successful
  "/blogs/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show blog
      responses:
        '200':
          description: successful
    put:
      summary: update blog
      responses:
        '200':
          description: successful
    delete:
      summary: delete blog
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
